site:
  name: EinfachSpanien
  site: 'https://einfachspanien.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: vuAnUe9xOFUvn99a1vni441c8CI8HMZqLPeFR5fXX9U

# Default SEO metadata
metadata:
  title:
    default: EinfachSpanien
    template: '%s'
  description: "Entdecken Sie umfassende Beratung und maßgeschneiderte Empfehlungen für Ihren Umzug nach Spanien. Sparen Sie bis zu 30% mit unseren Expertentipps zur Auswahl der besten Transportfirmen. Keine versteckten Kosten, vollständige Transparenz und Kundenzufriedenheit stehen bei uns an erster Stelle. Finden Sie Antworten auf alle Ihre Fragen zu unseren Preisen und Services in unserem FAQ-Bereich."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: EinfachSpanien
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@'
    site: 'https://einfachspanien.com'
    cardType: summary_large_image

i18n:
  language: de
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

analytics:
  vendors:
    googleAnalytics:
      id: "G-ZPF622P6EC" # or "G-XXXXXXXXXX"

ui:
  theme: 'light' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"

  tokens:
    default:
      fonts:
        sans: InterVariable
        serif: var(--ph-font-sans)
        heading: var(--ph-font-sans)
      colors:
        default: rgb(16 16 16)
        heading: rgb(0 0 0)
        muted: rgb(40 40 40)
        bgPage: rgb(255 255 255)
        primary: rgb(0 124 220)
        secondary: rgb(30 58 138)
        accent: rgb(109 40 217)
        info: rgb(119 182 234)
        success: rgb(54 211 153)
        warning: rgb(251 189 35)
        error: rgb(248 114 114)
        link: var(--ph-color-primary)
        linkActive: var(--ph-color-link)
    dark:
      fonts: {}
      colors:
        default: rgb(247, 248, 248)
        heading: rgb(247, 248, 248)
        muted: rgb(200, 188, 208)
        bgPage: rgb(3 6 32)
        primary: rgb(29 78 216)
        secondary: rgb(30 58 138)
        accent: rgb(135 77 2267)
        info: rgb(58 191 248)
        success: rgb(54 211 153)
        warning: rgb(251 189 35)
        error: rgb(248 114 114)
        link: var(--ph-color-primary)
        linkActive: var(--ph-color-link)
